airports:
  [
    "ORY",
    "NCE",
    "LYS",
    "TLS",
    "MRS",
    "BSL",
    "BOD",
    "NTE",
    "BVA",
    "RUN",
    "PTP",
    "LIL",
    "FDF",
    "MPL",
  ]

topic: captors/temperature
qos: 0
timeBtwData: 1
clientID: temperature_captor
# Has to be from enum in donnestruct
nature: temperature
